In [43]:
import numpy as np

binaryInput1 = '1010011'
binaryInput2 = '11010'

def process_inputs(input1, input2):
    if len(input1) > len(input2):
        for i in range(len(input1) - len(input2) + 1):
            input2 = "0" + input2
        input1 = "0" + input1
    if len(input2) > len(input1):
        for i in range(len(input2) - len(input1)+ 1):
            input1 = "0" + input1
        input2 = "0" + input2
        
    arr1 = np.fromstring(input1, np.int8) - 48
    arr2 = np.fromstring(input2, np.int8) - 48
        
    return arr1, arr2

# Input '1010011' & '11010'
#Output [1 0 1 0 0 1 1]
# and   [0 0 1 1 0 1 0]

In [44]:
#Adding
def add_binary(binaryInput1, binaryInput2):
    result = np.zeros(len(binaryInput1), dtype=int)
    result_overflow = np.zeros(len(binaryInput1), dtype=int)
    for i in range(len(binaryInput1)-1,0,-1):
        if binaryInput1[i] == 1 and binaryInput2[i] == 1:
            result_overflow[i-1] = 1
        if binaryInput1[i] == 0 and binaryInput2[i] == 1:
            result[i] = 1
        if binaryInput1[i] == 1 and binaryInput2[i] == 0:
            result[i] = 1
    
    if np.isin(1,result_overflow) == True:
        result = add_binary(result, result_overflow)
        
    is0 = True
    while is0 == True:
        if result[0] == 0:
            result = np.delete(result,0)
        else:
            is0 = False
            
    return result


input1, input2 = process_inputs(binaryInput1, binaryInput2)
print(add_binary(input1, input2))

#Input [1 0 1 0 0 1 1]
# and  [0 0 1 1 0 1 0]

#Generate: [0 0 0 0 0 0 0]
#Overwrite [1 0 0 1 0 0 1]
#+Overflow [0 1 0 0 1 0 0]
#Then iterate

[1 1 0 1 1 0 1]


/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_5741/2973775794.py:16: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr1 = np.fromstring(input1, np.int8) - 48
/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_5741/2973775794.py:17: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr2 = np.fromstring(input2, np.int8) - 48


In [45]:
#Subtracting

binaryInput1 = '1001'
binaryInput2 = '110'

def subtract_binary(binaryInput1, binaryInput2):
    
    result = np.zeros(len(binaryInput1),dtype=int)
    num1 = int("".join(map(str, binaryInput1)))
    num2 = int("".join(map(str, binaryInput2)))
    
    for i in range(len(binaryInput1)-1,0,-1):
        if binaryInput1[i] == 1 and binaryInput2[i] == 1:
            result[i] = 0
        if num1 > num2:
            if binaryInput1[i] == 1 and binaryInput2[i] == 0:
                result[i] = 1
            if binaryInput1[i] == 0 and binaryInput2[i] == 1:
                result[i] = 1
                is1 = False
                index = i - 1
                while is1 == False:
                    if binaryInput1[index] == 1:
                        binaryInput1[index] = 0
                        is1 = True
                    else:
                        binaryInput1[index] = 1
                        index -= 1
        if num1 < num2:
            if binaryInput1[i] == 0 and binaryInput2[i] == 1:
                result[i] = 1
            if binaryInput1[i] == 1 and binaryInput2[i] == 0:
                result[i] = 1
                is1 = False
                index = i - 1
                while is1 == False:
                    if binaryInput2[index] == 1:
                        binaryInput2[index] = 0
                        is1 = True
                    else:
                        binaryInput2[index] = 1
                        index -= 1
    
    is0 = True
    while is0 == True:
        if result[0] == 0:
            result = np.delete(result,0)
        else:
            is0 = False
    
    if num1 > num2:
        return result
    if num1 < num2:
        return '-' + np.array2string(result)
    
input1, input2 = process_inputs(binaryInput1, binaryInput2)
print(subtract_binary(input1, input2))

#Input [1 0 0 1]
# and  [0 1 1 0]
#Iterate backwards through larger number
#

[1 1]


/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_5741/2973775794.py:16: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr1 = np.fromstring(input1, np.int8) - 48
/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_5741/2973775794.py:17: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr2 = np.fromstring(input2, np.int8) - 48


In [46]:
#Multiplication

binaryInput1 = '11101'
binaryInput2 = '1001'

def multiply_binary(binaryInput1, binaryInput2):
    result = np.zeros(0,dtype=float)
    
    for i in range(len(binaryInput1)-1,0,-1):
        if binaryInput1[i] == 1:
            inst_sum = np.append(binaryInput2, np.zeros(len(binaryInput1)-i-1,dtype=int))
            result_format = np.insert(result, 0, np.zeros(len(inst_sum)-len(result),dtype=int))
            result = add_binary(result_format, inst_sum)
    
    is0 = True
    while is0 == True:
        if result[0] == 0:
            result = np.delete(result,0)
        else:
            is0 = False
    
    return result

input1, input2 = process_inputs(binaryInput1, binaryInput2)
print(multiply_binary(input1, input2))

[1 0 0 0 0 0 1 0 1]


/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_5741/2973775794.py:16: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr1 = np.fromstring(input1, np.int8) - 48
/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_5741/2973775794.py:17: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr2 = np.fromstring(input2, np.int8) - 48


In [47]:
#Division

binaryInput1 = '100110101'
binaryInput2 = '110'

def divide_binary(binaryInput1, binaryInput2):
    prov_div = np.array([0])
    result = np.array([0])
    
    for i in range(len(binaryInput1)):
        prov_div = np.append(prov_div, binaryInput1[i])
        if int("".join(map(str, prov_div))) > int("".join(map(str, binaryInput2))):
            result = np.append(result, 1)
            prov_div = subtract_binary(np.insert(prov_div, 0, np.zeros(len(binaryInput2)-len(prov_div))), binaryInput2)
        else:
            result = np.append(result, 0)
            
    is0 = True
    while is0 == True:
        if result[0] == 0:
            result = np.delete(result,0)
        else:
            is0 = False
            
    return result
    
input1, input2 = process_inputs(binaryInput1, binaryInput2)
print(divide_binary(input1, input2))

[1 1 0 0 1 1]


/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_5741/2973775794.py:16: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr1 = np.fromstring(input1, np.int8) - 48
/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_5741/2973775794.py:17: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr2 = np.fromstring(input2, np.int8) - 48
