In [37]:
import numpy as np

binaryInput1 = '1010011'
binaryInput2 = '11010'

def process_inputs(input1, input2):
    if len(input1) > len(input2):
        for i in range(len(input1) - len(input2) + 1):
            input2 = "0" + input2
        input1 = "0" + input1
    if len(input2) > len(input1):
        for i in range(len(input2) - len(input1)+ 1):
            input1 = "0" + input1
        input2 = "0" + input2
        
    arr1 = np.fromstring(input1, np.int8) - 48
    arr2 = np.fromstring(input2, np.int8) - 48
        
    return arr1, arr2

#Adding
def add_binary(binaryInput1, binaryInput2):
    result = np.zeros(len(binaryInput1), dtype=int)
    result_overflow = np.zeros(len(binaryInput1), dtype=int)
    for i in range(len(binaryInput1)-1,0,-1):
        print(i)
        if binaryInput1[i] == 1 and binaryInput2[i] == 1:
            result_overflow[i-1] = 1
        if binaryInput1[i] == 0 and binaryInput2[i] == 1:
            result[i] = 1
        if binaryInput1[i] == 1 and binaryInput2[i] == 0:
            result[i] = 1
    
    if np.isin(1,result_overflow) == True:
        result_f = add_binary(result, result_overflow)
    else:
        result_f = result
    
    return result_f


input1, input2 = process_inputs(binaryInput1, binaryInput2)
print(add_binary(input1, input2))

[0 1 0 1 0 0 1 1]
[0 0 0 1 1 0 1 0]
7
6
5
4
3
2
1
[0 0 1 0 0 1 0 0]
[0 1 0 0 1 0 0 1]
[0 1 0 0 1 0 0 1]
[0 0 1 0 0 1 0 0]
7
6
5
4
3
2
1
[0 0 0 0 0 0 0 0]
[0 1 1 0 1 1 0 1]
[0 1 1 0 1 1 0 1]


/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_64293/3373685737.py:16: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr1 = np.fromstring(input1, np.int8) - 48
/var/folders/mh/dn_3qv0s6dndm54j9k1xw61h0000gn/T/ipykernel_64293/3373685737.py:17: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  arr2 = np.fromstring(input2, np.int8) - 48


In [ ]:

#Subtracting
def subtract_binary(binaryInput1, binaryInput2):
    result = np.ones(len(binaryInput1))
    for i in range(len(binaryInput1)-1,0,-1):
        if binaryInput1[i] == '1' and binaryInput2[i] == '1':
            result[i] = '0'
        if binaryInput1[i] == '0' and binaryInput2[i] == '0':
            result[i] = '0'
        if binaryInput1 > binaryInput2:
            if binaryInput1[i] == '1' and binaryInput2[i] == '0':
                result[i] = '1'
            # 0 - 1 -> result digit set to 1, subtract 1 from above place
        if binaryInput1 < binaryInput2:
            if binaryInput1[i] == '0' and binaryInput2[i] == '1':
                result[i] = '1'
            # 0 - 1 -> result digit set to 1, subtract 1 from above place
    if binaryInput1 > binaryInput2:
        result = np.array2string(result)
    if binaryInput1 < binaryInput2:
        result = '-' + np.array2string(result)
    
#Multiplication

#Division